from typing import TypedDict, List, Dict, Optional, Any
# pyrefly: ignore [missing-import]
from langgraph.graph import StateGraph, END
from core.brain import brain
from core.actions.manager import action_manager
from loguru import logger


# 1. State Definition: This represents Ritu's 'Working Memory'
class RituState(TypedDict):
    input: str  # User's raw input message
    chat_history: List[Dict]  # Historical record of the conversation
    action: Optional[str]  # Extracted or identified Action name
    param: Optional[str]  # Extracted parameters for the action
    response: str  # Direct text response from the LLM
    raw_ai_response: Dict[str, Any]  # The complete original output dictionary from brain.chat
    final_output: str  # The final text that will be processed by the TTS engine


# --- Nodes: Main execution stations of the graph ---

def ritu_brain_node(state: RituState):
    """
    Listens to the user query and routes decision making through Brain (Ollama).
    """
    logger.info(f"🧠 Ritu thinking... Input: {state['input']}")

    # Utilizing your original brain.chat logic (Variable names strictly preserved)
    result = brain.chat(state['input'])

    # Print raw output structure inside terminal logs for easier debugging
    logger.debug(f"Brain Raw Output: {result}")

    # Returning dictionary updates to synchronize keys back with State channels
    return {
        "action": result.get("action"),
        "param": result.get("param"),
        "response": result.get("response"),
        "raw_ai_response": result,
        "final_output": result.get("response")
    }


def ritu_action_node(state: RituState):
    """
    Executes the recognized automated tasks using action_manager.
    """
    # We bypass the strict action string check here because action_manager
    # has robust fallback logic to parse actions directly from the raw text.
    logger.info(f"🛠️ [ACTION NODE] Parsing text for actions...")

    try:
        # Route processing down to your original action_manager workflow
        action_result = action_manager.parse_and_execute(state['raw_ai_response'])

        # If the manager successfully returns confirmation text, we pass it forward to TTS
        # Otherwise, fall back to the verbal phrase generated by the LLM node
        return {"final_output": action_result if action_result else state["response"]}

    except Exception as e:
        logger.error(f"❌ Action Failed: {e}")
        return {"final_output": f"अरे बाबा, कुछ गड़बड़ हो गई!"}


# --- Graph Construction: Architecture Setup ---

# Instantiate core graph wrapper binding state dictionary model
workflow = StateGraph(RituState)

# Register execution stations as active Nodes
workflow.add_node("brain", ritu_brain_node)
workflow.add_node("action", ritu_action_node)

# Set the primary operational point of entry
workflow.set_entry_point("brain")

# Always route to action node so the robust Action Manager fallback logic can parse the raw text
workflow.add_edge("brain", "action")

# Terminate pipeline workflow after action script executes completely
workflow.add_edge("action", END)

# Final engine compilation compilation phase
ritu_app = workflow.compile()

logger.success("✅ Ritu LangGraph Engine Ready!")